   stages:
     - build

   build_windows:
     stage: build
     tags:
       - windows
     script:
       - npm install
       - npm run build:win
     artifacts:
       paths:
         - dist/**/*.exe
